### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by stevenmusumeche** [shelfio/ghostscript-lambda-layer#10]
Is it possible for someone to self host this layer within their own account?  I am concerned with using the arn and it being removed in the future.

**Comment by vladgolubev** [comment]
@stevenmusumeche 

AWS doesn't allow to remove lambda layers at all. Once they are published - they are public forever. So there is no risk of it disappearing.

Also, if you still want to host it yourself - check out how to download layer zip https://stackoverflow.com/questions/56614037/how-to-download-aws-lambda-layer

Or just grab `ghostscript.zip` file from this repo and publish it yourself. See `publish.sh` for details

**Comment by vladgolubev** [comment]
To correct myseylf. I can delete layer version but code will still work

> The creator of a layer can delete the version of the layer that you're using. When this happens, your function continues to run as though the layer version still existed.

https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html
